project:
  type: website
  output-dir: _site

website:
  title: "Job Market Analysis 2024"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: Introduction.qmd
        text: "Introduction"
      - href: data_analysis.qmd
        text: "Data Analysis"
      - href: career_plan.qmd
        text: "Career Strategy"
      - href: skill_gap_analysis.qmd/ipynb
        text: "Skill Gap Analysis"
format:
  html:
    theme: cosmo
    toc: true
execute:
  echo: true
  eval: true
  code-fold: true